# Generated by Django 3.0.6 on 2021-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210506_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
