# Generated by Django 3.0.6 on 2021-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contacts',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('profile', models.ManyToManyField(related_name='user_contacts', to='main_app.Profile')),
            ],
        ),
    ]
